import React from 'react';
import Header from '../../common/parts/Header';
import Footer from '../../common/parts/Footer';

function Terms() {
    return (
        <div className="">
            <Header />
            <div className="px-4 py-12 mx-auto text-gray-800 max-w-7xl sm:px-6 lg:px-8">
                <h1 id='privacy-policy' className="text-4xl font-bold text-start ">Privacy Policy</h1>
                <p className="mb-8 text-sm text-gray-600 text-start">Last updated: December 19, 2024</p>

                <section className="mb-8">
                    <p className="mb-4">
                        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                    </p>
                    <p className="mb-4">
                        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="mb-4 text-2xl font-semibold">Interpretation and Definitions</h2>
                    <h3 className="mb-2 text-xl font-medium">Interpretation</h3>
                    <p className="mb-4">
                        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                    </p>

                    <h3 className="mb-2 text-xl font-medium">Definitions</h3>
                    <p className="mb-4">For the purposes of this Privacy Policy:</p>
                    <ul className="pl-6 space-y-2 list-disc">
                        <li><strong>Account:</strong> A unique account created for You to access our Service or parts of our Service.</li>
                        <li><strong>Affiliate:</strong> An entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</li>
                        <li><strong>Company:</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Webweave.</li>
                        <li><strong>Cookies:</strong> Small files placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                        <li><strong>Country:</strong> Refers to Tamil Nadu, India.</li>
                        <li><strong>Device:</strong> Any device that can access the Service such as a computer, cellphone, or digital tablet.</li>
                        <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</li>
                        <li><strong>Service:</strong> Refers to the Website.</li>
                        <li><strong>Service Provider:</strong> Any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</li>
                        <li><strong>Third-party Social Media Service:</strong> Any website or social network through which a User can log in or create an account to use the Service.</li>
                        <li><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit).</li>
                        <li><strong>Website:</strong> Refers to Webweave, accessible from <a href="https://Webweavek.vercel.app" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Webweavek.vercel.app</a>.</li>
                        <li><strong>You:</strong> The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                    </ul>
                </section>

                <section id='data-collect' className="mb-8">
                    <h2 className="mb-4 text-2xl font-semibold">Collecting and Using Your Personal Data</h2>

                    <h3 className="mb-2 text-xl font-medium">Types of Data Collected</h3>

                    <h4 className="mb-2 text-lg font-medium">Personal Data</h4>
                    <p className="mb-4">
                        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                    </p>
                    <ul className="pl-6 space-y-2 list-disc">
                        <li>Email address</li>
                        <li>First name and last name</li>
                        <li>Social Profile image</li>
                        <li>Usage Data</li>
                    </ul>

                    <h4 className="mt-6 mb-2 text-lg font-medium">Usage Data</h4>
                    <p className="mb-4">
                        Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.
                    </p>
                </section>

                <section className="p-6 bg-gray-100 rounded-lg">
                    <h2 className="text-2xl font-semibold">Contact Us</h2>
                    <p className='mb-4' >If you have any questions about this Privacy Policy, you can contact us:</p>
                    <ul className="pl-6 space-y-2 list-disc">
                        <li>
                            <span className="font-medium">By email:</span> <a href="mailto:shanmugamsanthosh22@gmail.com" className="text-blue-500 hover:underline">shanmugamsanthosh22@gmail.com</a>
                        </li>
                        <li>
                            <span className="font-medium">By visiting this website:</span> <a href="https://santechh.vercel.app" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">santechh.vercel.app</a>
                        </li>
                    </ul>
                </section>
            </div>
            <Footer />
        </div>
    );
}

export default Terms;
